### ISSUE TITLE
Mana bars

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#96]
Plan A.
In this older GUI version of the same system the bars work for enemeies
https://www.hiveworkshop.com/threads/gui-heath-mana-bar-system-v1-5.245840/
And there's a way to remove the game's health bars apparently 
https://www.thehelper.net/threads/remove-a-units-health-bar-but-keep-it-selectable.116985/
I prefer this option if it can be done.

Plan B.
https://www.hiveworkshop.com/threads/progressbar-v2.223392/
Only if it can be scaled down and placement needs to be adjusted.

**Comment by FlyOutBoy** [comment]
done

**Comment by tpdjairks** [comment]
![image](https://user-images.githubusercontent.com/110841373/186557301-6fe90462-d3da-4191-aba7-50fc4cfce484.png)
Can you make it like this maybe with 4 lines showing 25%, 50%, 75%, 100% for some extra clarity? The normal HP bar turns from green to red as you go low on HP but don't need to be as complex as that.

And I would like a few adjustments in relation to it also as following.
-camera 100 looks like this
![image](https://user-images.githubusercontent.com/110841373/186557587-e2ddbc96-4980-470e-96b6-1d4885530704.png)
-camera 120 looks like this
![image](https://user-images.githubusercontent.com/110841373/186557623-c756c2d7-e779-4c72-af81-206899e358cf.png)

So the adjustments that I have in mind are:

1.  Make the bars slimmer / thinner. They're a bit too fat as you can see above.
2. Adjust default camera view to -camera 100 equivalent and set it to Minimum.
3. Adjust Max. camera to -camera 120,
+
4, The 4 lines showing 25%, 50%, 75%, 100% of hp.

**Comment by tpdjairks** [comment]
You used Selection 0. I told you Selection -10 omg. I fixed it myself <.< 
No need to even resize it anymore cuz I switched bars Selection from 0.10 to 0.8 and now they're ok~ish.
Random normal hp bars appearing out of nowhere bug is fixed now.
But this bug is still present sometimes.
![image](https://user-images.githubusercontent.com/110841373/186576553-194ddb2c-2bf7-4551-b5c6-c39342f17ae7.png)

To do:
+ add this to it. 4 lines to show 25%. 50%, 75%, 100% HP, for clarity. Old bars show green to red HP when you take dmg. 
![image](https://user-images.githubusercontent.com/110841373/186574145-a8e96c5a-9c07-4c8e-8b2a-ebd29df16441.png)
+ camera adjustments: Default + Min -camera 100, Max -camera 120 because the bars change size across different zoom level so this is to minimize that.
+ try to fix the bug in the 1st picture above with bars staying after death sometimes.
+ add the bars to Nami clones as well and this should be officially over. 

![image](https://user-images.githubusercontent.com/110841373/186579824-aa4fe595-02a1-4113-adc9-b2c5e6a0c2a0.png)


Here's the updated map btw,
https://drive.google.com/file/d/1_bKOxUO7Dpo5A5h3XQI6Fp1xorHzo9Un/view?usp=sharing

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/186655810-54ef080a-44ad-4168-882a-8b312e8b46c6.png)

https://user-images.githubusercontent.com/33839947/186655860-a6810e27-8d4c-4e64-9858-429821c16f63.mp4

**Comment by tpdjairks** [comment]
Invisible units still have the bars even if invisible and enemy can see their location.

**Comment by FlyOutBoy** [comment]
done

**Comment by tpdjairks** [comment]
Final adjustment? xD

Watch how it looks from the sides. Shouldn't they be synced? 
![image](https://user-images.githubusercontent.com/110841373/186913007-a2555226-89ee-4923-b5f4-5c0f48e556e2.png)
![image](https://user-images.githubusercontent.com/110841373/186913076-07d2f72a-daf7-446f-8ea0-5a3deabaf534.png)

**Comment by FlyOutBoy** [comment]
It because viev angle
